name: CI

on: 
  pull_request:
    branches: 
      - master
      - develop

jobs:
  test:
    name: Run tests when pull request is trigger
    runs-on: [ubuntu-latest]
    steps:
      - name: npm install, test
        run: |
          npm install
          npm test
